project:
  title: "UWB-thesis"
format:
  html:
    self-contained: true
listing: default
pdf-engine: xelatex
author: Vit Petrik
bibliography: citation.bib
csl: ctustyle/style.csl
date: last-modified
tbl-cap-location: bottom
code-line-numbers: true
execute:
  echo: false
  output: false
crossref:
  ref-hyperlink: true # (default is true)
  fig-prefix: ""   # (default is "Figure")
  tbl-prefix: ""    # (default is "Table")
  eq-prefix: ""
  