project:
  title: "UWB-thesis"
format:
  html:
    self-contained: true
listing: default
pdf-engine: xelatex
author: Vit Petrik
bibliography: citation.bib
csl: ctustyle/style.csl
date: last-modified
tbl-cap-location: bottom
code-line-numbers: true
