project:
  type: book

book:
  title: "Fusion of UWB-Based Distance Sensors with a Visual Relative Localization System"
  author: "Vit Petrik"
  date: last-modified
  chapters:
    - index.qmd
    - chapters/2_uvdar.qmd
    - chapters/3_uwb.qmd
    - chapters/4_kalman.qmd
    - chapters/5_implementation.qmd
    - chapters/6_experiments.qmd
    - chapters/7_conclusion.qmd
    - chapters/references.qmd
format:
  html:
    theme: cosmo
  ctu-thesis-pdf:
    link-citations: true
    include-in-header: 
        text: |
          \usepackage{makeidx}
          \makeindex
    include-after-body: 
        text: |
          \printindex
jupyter: julia-1.8
listing: default
pdf-engine: xelatex
author: Vit Petrik
bibliography: citation.bib
csl: ctustyle/style.csl
date: last-modified
tbl-cap-location: bottom
code-line-numbers: true
execute:
  echo: false
  output: false
crossref:
  ref-hyperlink: true # (default is true)
  fig-prefix: ""   # (default is "Figure")
  tbl-prefix: ""    # (default is "Table")
  eq-prefix: ""
  