In recent years, the use of unmanned aerial vehicles (UAVs) has been rapidly growing due to their versatility and wide range of applications, from aerial photography and surveillance to delivery services [^zipline] and search and rescue operations @petrlik2023uavs. 
The problem of relative localization in UAV swarms is a critical challenge in enabling cooperative behavior and avoiding collisions.

To address this problem, a novel system is proposed in this thesis that combines computer vision and ultra-wideband (UWB) technology for direction and range measurements, respectively. 
By combining these measurements with a Kalman filter, the relative positions and orientations of UAVs can be estimated with high accuracy, even in GNSS-denied environments such as buildings or underground areas @petrlik2023uavs. 
This approach has a significant advantage over existing methods, which often rely on GNSS @6943105 or motion capture [^optitrack] and are therefore limited in their ability to operate in challenging environments or without additional infrastructure onsite.

This thesis addresses designing and implementing an effective relative localization system for UAV swarms using computer vision and UWB technology and evaluates how well it performs in real-world scenarios. 
First, a review of the proposed system and its key components, including the computer vision algorithms for direction estimation and the UWB hardware for range measurement, will be presented. 
Finally, the performance of the system will be evaluated through a series of experiments in both simulated and real-world environments.

By developing and testing this system, a contribution will be made to the growing body of research on multi-robot systems and pave the way for new applications of UAV swarms in challenging environments.

[^zipline]: Blood and packages delivery <https://www.flyzipline.com>
[^optitrack]: Motion capture OptiTrack <https://optitrack.com>

## State of the art

Extensive research has already been conducted on the utilization of Ultra-Wideband (UWB) technology in Unmanned Aerial Vehicle (UAV) applications.
Majority of published articles primarily concentrate on the implementation of UWB technology using an architecture based on UWB anchors  [@7743707; @Cao2018/03].
Nevertheless, this particular implementation is unsuitable for deployment in potentially hazardous environments, particularly for search and rescue applications.
Article *Decentralized Visual-Inertial-UWB Fusion for Relative State Estimation of Aerial Swarm* [@9196944] proposes system architecture and the fusion algorithm, which combines visual-inertial odometry (VIO) and UWB ranging measurements in a tightly-coupled manner. However, this approach would be ineffective in environments lacking distinct features.

Hence, the subsequently proposed system stands out for its exceptional ease of deployment, accuracy of measurements and the robustness it offers.

## Ranging and positioning in Civil Aviation

Along with the widely adopted localization and navigation via GNSS, aviation has developed several ranging and positioning solutions that can be analyzed and used to take a cue from for utilization in UAV applications.

### En-route positioning and navigation {.unnumbered .unlisted}

DME (Distance Measuring Equipment) is a type of radio navigation equipment that provides an accurate slant range from the aircraft to selected ground-based DME station. The DME uses the transmission of UHF band radio signals between aircraft and ground station on the principle of two-way ranging [@atlantic]. DME consists of ground transponders and aircraft on-board avionics. Aircraft DME avionics first interrogate ground transponders, and the transponder replies back to avionics through a pair of pulses. The time elapsed from the interrogation to the receipt of the replies from the ground transponder is measured and when the internal processing delay of the ground equipment computer is known, a distance representing slant range between aircraft and the ground station can be determined [@radionavigation].

Over the time, DME has become an indispensable component of air traffic positioning and navigation during various phases of flight including departure, en-route flight, approach, landing or even missed approach procedure [@pbn]. It often works as a complement to other systems such as VOR, ILS or MLS, further increasing its versatility. With advancements in technology, the latest generation of DME transponders surpass the outdated operational standards, delivering improved navigational performance in accordance with specification required by Performance Based Navigation (PBN) standard of ICAO. 

### Aircraft-to-Aircraft positioning {.unnumbered .unlisted}

The aviation in general prides itself on a reputation of safe and well managed mean of transport with use of state-of-the-art equipment, procedures and training. Besides other safety related aspects, the aircraft-to-aircraft separation is a crucial when navigating the aircraft along the flight route from the very beginning of the flight till disembarking at the destination.

Development and incorporation of the Traffic Alert and Collision Avoidance System (TCAS) in the late 1980s into the aircraft systems serves as an effective solution to mitigate the risk of midair collisions between individual aircraft [@faa].

TCAS is a current implementation of the ICAO Airborne Collision Avoidance System (ACAS) technical standard and is a family of airborne devices that operate autonomously, independently from the ground-based air traffic control (ATC) and are designed to offer collision avoidance protection [@eurocontrol; @faa]. The concept of TCAS comprises of specialized TCAS computer unit and simultaneously takes advantage of already existing 
on-board equipment, the transponder of secondary surveillance radar.

The use of radar beacon transponders installed on aircraft for ground ATC purposes and provides no protection against an aircraft, that do not possess an operating transponder [@henely].
